### ISSUE TITLE
these are the 5 errors i got and i have no idea how to fix them

### ISSUE THREAD

**Issue by Silverfang12** [samjesus8/YouTube-CSharp-Discord-Bot#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'DiscordApiClient' does not contain a definition for 'ConnectAsync' and no accessible extension method 'ConnectAsync' accepting a first argument of type 'DiscordApiClient' could be found (are you missing a using directive or an assembly reference?)	riza bot	C:\Users\erik\source\repos\New folder\riza bot\rixa bot\riza bot\Bot.cs	54	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1929	'DiscordApiClient' does not contain a definition for 'UseInteractivity' and the best extension method overload 'ClientExtensions.UseInteractivity(DiscordClient, InteractivityConfiguration)' requires a receiver of type 'DiscordClient'	riza bot	C:\Users\erik\source\repos\New folder\riza bot\rixa bot\riza bot\Bot.cs	42	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'Task' does not contain a definition for 'CompleteTask'	riza bot	C:\Users\erik\source\repos\New folder\riza bot\rixa bot\riza bot\Bot.cs	59	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'DSharpPlus.DiscordClient' to 'DSharpPlus.Net.DiscordApiClient'	riza bot	C:\Users\erik\source\repos\New folder\riza bot\rixa bot\riza bot\Bot.cs	41	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0106	The modifier 'private' is not valid for this item	riza bot	C:\Users\erik\source\repos\New folder\riza bot\rixa bot\riza bot\Bot.cs	57	Active

**Comment by samjesus8** [comment]
right can you show me your code, it looks like u havent created the ConnectAsync method judging from the first error

**Comment by Silverfang12** [comment]
I manage to fix it and its online thanks for replying Sent from Mail for Windows From: Samuel JesuthasSent: Saturday, January 28, 2023 3:56 PMTo: samjesus8/YouTube-CSharp-Discord-BotCc: Silverfang12; AuthorSubject: Re: [samjesus8/YouTube-CSharp-Discord-Bot] these are the 5 errors i got and i have no idea how to fix them (Issue #1) right can you show me your code, it looks like u havent created the ConnectAsync method judging from the first error—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by samjesus8** [comment]
Alright, u might wanna learn how to use markdown language too lmao.

But if its online and working thats cool
